name: Print workflow

on: workflow_dispatch

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello"

  print_dev:
    runs-on: ubuntu-latest
    needs: print_hello
    if: success()
    environment: dev
    steps:
      - name: Print dev
        run: echo "dev"
        
  print_prod:
    runs-on: ubuntu-latest
    needs: print_hello
    if: success()
    environment: prod
    steps:
      - name: Print prod
        run: echo "prod"
