name: Print workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello"

  print_dev:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev'
    needs: print_hello
    steps:
      - name: Print dev
        run: echo "dev"
        
  print_prod:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'prod'
    needs: print_hello
    steps:
      - name: Print prod
        run: echo "prod"
